### ISSUE TITLE
3.8 compatibility

### ISSUE THREAD

**Issue by afbora** [bnomei/kirby3-cloudconvert#16]
> 
> Fatal error: Uncaught Whoops\Exception\ErrorException: include(D:\xampp\htdocs\test\kirby\4713\site\plugins\kirby3-cloudconvert-1.1.9\vendor\composer/../../tests/kirby/src/Cms/Event.php): Failed to open stream: No such file or directory in D:\xampp\htdocs\test\kirby\4713\kirby\vendor\composer\ClassLoader.php:571 Stack trace: #0 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\composer\ClassLoader.php(571): Whoops\Run->handleError() #1 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\composer\ClassLoader.php(571): include() #2 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile() #3 D:\xampp\htdocs\test\kirby\4713\kirby\src\Cms\App.php(1688): Composer\Autoload\ClassLoader->loadClass() #4 D:\xampp\htdocs\test\kirby\4713\kirby\src\Cms\AppErrors.php(178): Kirby\Cms\App->trigger() #5 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\filp\whoops\src\Whoops\Handler\CallbackHandler.php(50): Kirby\Cms\App->Kirby\Cms\{closure}() #6 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\filp\whoops\src\Whoops\Run.php(370): Whoops\Handler\CallbackHandler->handle() #7 [internal function]: Whoops\Run->handleException() #8 {main} thrown in D:\xampp\htdocs\test\kirby\4713\kirby\vendor\composer\ClassLoader.php on line 571
> 
> Fatal error: Uncaught Error: Class "Kirby\Cms\Event" not found in D:\xampp\htdocs\test\kirby\4713\kirby\src\Cms\App.php:1688 Stack trace: #0 D:\xampp\htdocs\test\kirby\4713\kirby\src\Cms\AppErrors.php(178): Kirby\Cms\App->trigger() #1 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\filp\whoops\src\Whoops\Handler\CallbackHandler.php(50): Kirby\Cms\App->Kirby\Cms\{closure}() #2 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\filp\whoops\src\Whoops\Run.php(370): Whoops\Handler\CallbackHandler->handle() #3 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\filp\whoops\src\Whoops\Run.php(454): Whoops\Run->handleException() #4 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\composer\ClassLoader.php(571): Whoops\Run->handleError() #5 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\composer\ClassLoader.php(571): include('...') #6 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile() #7 D:\xampp\htdocs\test\kirby\4713\kirby\src\Cms\App.php(1688): Composer\Autoload\ClassLoader->loadClass() #8 D:\xampp\htdocs\test\kirby\4713\kirby\src\Cms\AppErrors.php(178): Kirby\Cms\App->trigger() #9 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\filp\whoops\src\Whoops\Handler\CallbackHandler.php(50): Kirby\Cms\App->Kirby\Cms\{closure}() #10 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\filp\whoops\src\Whoops\Run.php(370): Whoops\Handler\CallbackHandler->handle() #11 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\filp\whoops\src\Whoops\Run.php(454): Whoops\Run->handleException() #12 D:\xampp\htdocs\test\kirby\4713\kirby\vendor\filp\whoops\src\Whoops\Run.php(486): Whoops\Run->handleError() #13 [internal function]: Whoops\Run->handleShutdown() #14 {main} thrown in D:\xampp\htdocs\test\kirby\4713\kirby\src\Cms\App.php on line 1688

**Comment by afbora** [comment]
Duplicated with https://github.com/bnomei/kirby3-cloudconvert/issues/12
